

DEFAULT_IGNORE_PATTERNS = [
    # Version control
    ".git",
    ".svn",
    ".hg",
    ".bzr",
    ".fossil",
    "_darcs",
    "CVS",
    # Python
    "__pycache__",
    "*.py[cod]",
    "*.so",
    ".venv",
    "venv",
    "env",
    ".Python",
    "pip-log.txt",
    "pip-delete-this-directory.txt",
    ".tox",
    ".coverage",
    ".coverage.*",
    ".cache",
    "nosetests.xml",
    "coverage.xml",
    "*.cover",
    ".hypothesis",
    ".pytest_cache",
    # JavaScript / Node.js
    "node_modules",
    "jspm_packages",
    "bower_components",
    ".npm",
    ".eslintcache",
    ".node_repl_history",
    "*.tsbuildinfo",
    ".next",
    ".nuxt",
    ".vuepress/dist",
    ".serverless",
    ".fusebox",
    ".dynamodb",
    # Ruby
    "*.gem",
    "*.rbc",
    "/.config",
    "/coverage",
    "/InstalledFiles",
    "/pkg",
    "/spec/reports",
    "/test/tmp",
    "/test/version_tmp",
    "/tmp",
    ".rakeTasks",
    ".rspec",
    ".rspec_status",
    # Java
    "*.class",
    "*.log",
    "*.ctxt",
    ".mtj.tmp",
    "*.jar",
    "*.war",
    "*.nar",
    "*.ear",
    "*.zip",
    "*.tar.gz",
    "*.rar",
    "hs_err_pid*",
    ".gradle",
    "build",
    "out",
    # C/C++
    "*.o",
    "*.ko",
    "*.obj",
    "*.elf",
    "*.ilk",
    "*.map",
    "*.exp",
    "*.gch",
    "*.pch",
    "*.lib",
    "*.a",
    "*.la",
    "*.lo",
    "*.dll",
    "*.so",
    "*.so.*",
    "*.dylib",
    # Rust
    "target",
    "**/*.rs.bk",
    "Cargo.lock",
    # Go
    "*.exe",
    "*.test",
    "*.prof",
    "*.out",
    # Swift / Objective-C
    ".build",
    "Packages",
    "xcuserdata",
    "*.xcscmblueprint",
    "*.xccheckout",
    "build",
    "DerivedData",
    "*.moved-aside",
    "*.pbxuser",
    "!default.pbxuser",
    "*.mode1v3",
    "!default.mode1v3",
    "*.mode2v3",
    "!default.mode2v3",
    "*.perspectivev3",
    "!default.perspectivev3",
    "*.hmap",
    "*.ipa",
    "*.dSYM.zip",
    "*.dSYM",
    # Android
    "*.apk",
    "*.ap_",
    "*.dex",
    "*.class",
    "bin",
    "gen",
    "proguard",
    # iOS
    "*.ipa",
    "*.xcarchive",
    "*.dSYM.zip",
    "*.dSYM",
    # IDEs and editors
    ".idea",
    ".vscode",
    "*.swp",
    "*.swo",
    "*~",
    ".vs",
    "*.sublime-workspace",
    ".atom",
    ".buildpath",
    ".project",
    ".settings",
    "*.launch",
    "*.tmproj",
    "*.esproj",
    "nbproject",
    "*.iml",
    "*.ipr",
    "*.iws",
    # OS generated
    ".DS_Store",
    ".DS_Store?",
    "._*",
    ".Spotlight-V100",
    ".Trashes",
    "ehthumbs.db",
    "Thumbs.db",
    "desktop.ini",
    # Build outputs
    "dist",
    "build",
    "out",
    "bin",
    "target",
    # Logs and databases
    "*.log",
    "*.sql",
    "*.sqlite",
    "*.db",
    # Package management
    "package-lock.json",
    "yarn.lock",
    "pnpm-lock.yaml",
    "composer.lock",
    "Gemfile.lock",
    "Pipfile.lock",
    "poetry.lock",
    # Temporary files
    "*.tmp",
    "*.temp",
    "*.bak",
    "*.swp",
    "*.swo",
    "*~",
    # Configuration
    ".env",
    ".env.*",
    "config.local.js",
    "config.local.php",
    # Documentation
    "site",
    # Misc
    ".sass-cache",
    ".grunt",
    ".webpack",
    "*.pid",
    "*.seed",
    "dump.rdb",
    ".eslintcache",
    ".stylelintcache",
    ".tsbuildinfo",
    ".turbo",
    # Large media files
    "*.mp4",
    "*.tiff",
    "*.avi",
    "*.flv",
    "*.mov",
    "*.wmv",
]
